name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 16 * * *' # 每天 UTC 时间 16:00 执行（即北京时间 00:00）
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master # 指定检出master分支

      - name: Get the last successful workflow run
        id: get_last_run
        run: |
          last_run=$(gh api -X GET /repos/${{ github.repository }}/actions/runs?status=success&per_page=1 | jq -r '.workflow_runs[0].created_at')
          echo "LAST_RUN=${last_run}" >> $GITHUB_ENV

      - name: Check for new commits
        id: check_changes
        run: |
          if [ -z "$LAST_RUN" ]; then
            echo "First run detected, marking as true."
            echo "IS_CHANGED=true" >> $GITHUB_ENV
          else
            new_commits=$(git log --since="$LAST_RUN" --oneline)
            if [ -n "$new_commits" ]; then
              echo "Changes detected."
              echo "IS_CHANGED=true" >> $GITHUB_ENV
            else
              echo "No Changes found."
              echo "IS_CHANGED=false" >> $GITHUB_ENV
            fi
          fi

      - name: Deploy to GitHub Pages
        if: ${{ env.IS_CHANGED == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # 指定要发布的目录
